baseURL = "https://chronologos.github.io"
languageCode = "en-us"
title = "Ian"
theme = "beautifulhugo"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "bw"
[params]
hasNavbarBrand = false
[author]
name = "Ian Tay"
[[menu.main]]
  name = "posts"
  title = "blog section"
  weight = -110
  identifier = "blog"
  url = "/posts"
[blackfriday]
  extension = ["footnotes"]
[taxonomies]
  tag = "tags"
